// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0RZkjctWuzoq4cgiuDRZamBWvKlFbHg',
    appId: '1:550367582740:web:4c7fcffc4dcf722f9f6501',
    messagingSenderId: '550367582740',
    projectId: 'sih-tourist-safety-20385',
    authDomain: 'sih-tourist-safety-20385.firebaseapp.com',
    storageBucket: 'sih-tourist-safety-20385.firebasestorage.app',
    measurementId: 'G-JC69NH6BN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0RZkjctWuzoq4cgiuDRZamBWvKlFbHg',
    appId: '1:550367582740:android:4c7fcffc4dcf722f9f6501',
    messagingSenderId: '550367582740',
    projectId: 'sih-tourist-safety-20385',
    storageBucket: 'sih-tourist-safety-20385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR0RZkjctWuzoq4cgiuDRZamBWvKlFbHg',
    appId: '1:550367582740:ios:4c7fcffc4dcf722f9f6501',
    messagingSenderId: '550367582740',
    projectId: 'sih-tourist-safety-20385',
    storageBucket: 'sih-tourist-safety-20385.firebasestorage.app',
    iosBundleId: 'com.example.tourist_geo_fencing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR0RZkjctWuzoq4cgiuDRZamBWvKlFbHg',
    appId: '1:550367582740:macos:4c7fcffc4dcf722f9f6501',
    messagingSenderId: '550367582740',
    projectId: 'sih-tourist-safety-20385',
    storageBucket: 'sih-tourist-safety-20385.firebasestorage.app',
    iosBundleId: 'com.example.tourist_geo_fencing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR0RZkjctWuzoq4cgiuDRZamBWvKlFbHg',
    appId: '1:550367582740:windows:4c7fcffc4dcf722f9f6501',
    messagingSenderId: '550367582740',
    projectId: 'sih-tourist-safety-20385',
    authDomain: 'sih-tourist-safety-20385.firebaseapp.com',
    storageBucket: 'sih-tourist-safety-20385.firebasestorage.app',
  );
}
